### PR TITLE
bridge to catalog transition

### PR DESCRIPTION
**Pull request by Thanood**
- [ ] disable variations row if supportsVariations !== true
- [ ] include `numeric` and `moment` in sample dependencies

### CODE REVIEW

**Comment by adriatic** [comment]
I just love your systematic approach, Daniel!

Please keep all these changes somewhere, as it will be great data for ACT (Aurelia Configuration Tool) rules database

**Comment by vegarringdal** [comment]
See you have removed them menu, maybe we should have a simple menu option so you can have categories, like in my grid you can make the column in 3 ways, so thinking some basic samples on how to add filter/sorting etc for all 3 would be nice, if I have 1 long list it might be a bit messy. 
Simple json file under samples, "menu.json" the ref to folders in the sample folder.

**Comment by Thanood** [comment]
I'm not sure how that will actually look like.. :smile: 
I mean maybe it would be better to show these variations in another tab.

Or even make something like Aurelia's docs have done when switching from TypeScript to ES6. So you set the catalog once to, say, "Show me examples on how to do this with custom elements". And the catalog would show only these (**if** there are variations and of course, users could switch everytime).

I don't know if that would fit.

Personally, I like the tab approach. :smile:

**Comment by Thanood** [comment]
image

**Comment by vegarringdal** [comment]
I was thinking something like this, then each of those goes to separate folder.
Then of the first 5-10 I would show how to do the same with all 3 ways of doing it, and 4-x would have other samples

image

**Comment by vegarringdal** [comment]
Ill make a sample to night/tomorrow and show what I was thinking then you guys can tell me if you like it or not, then we modify it to something that we are all happy with.

**Comment by adriatic** [comment]
Yes, I would prefer that approach instead of forcing my view on Vegar :-). There is a caveat though, defined as the following three statements:

1. We need to have the same look and feel for all bridges (bridges in the sense that they represent a given third party SDK as a collection of Aurelia components).

2. Even more importantly, the related catalog apps should be as close to identical as the context allows us. Catalog is as much a marketing tool as a developer's online documentation; if not already, pretty soon will it become obvious that the uniformity and the depth of our bridges is a very strong asset. 
3. Since KendoUI is the "trend-setter" and many companies have praised the KendoUI catalog UI, I would like to use that as the standard for other bridges (Materialize and Syncfusion are a good examples of following that lead)

**Comment by vegarringdal** [comment]
Played around with a little
Something like this Im thinking (made most basic sample just to get a grid in there)
Using @Thanood v-grid atm that I downloaded a copy of (with some tweeks)

image

**Comment by Thanood** [comment]
@vegarringdal What part of the UI would these buttons actually change?
I'm guessing the code preview only.

While that would perfectly translate to just have more tabs on the code preview section we'd lose the "immediately check if it runs" capability. So I like your idea. :smile: 
The only concern I have with this is on a small screen (f.i. mobile) the four buttons will be on top of each other filling a lot of screen estate.

Maybe we can make these collapsible on mobile.

**Comment by Thanood** [comment]
@adriatic 
> Even more importantly, the related catalog apps should be as close to identical as the context allows us.

The above mentioned menu would of course be special to `v-grid` or at least libraries which support multiple approaches of implementing their components. I don't think this is a general feature for all catalogs.

**Comment by vegarringdal** [comment]
> While that would perfectly translate to just have more tabs in the code preview section we'd lose the "immediately check if it runs" capability. So I like your idea. :smile: 

many of the first buttons will be the same in 3 first ones, but Im doing that just to show how to achieve same result in 3 ways filter, select column, sortable headers, resizable headers (and for bug testing) Tht way you can go to the grid you are using

> The only concern I have with this is on a small screen (f.i. mobile) the four buttons will be on top of each other filling a lot of screen estate.
Well its simple, not everything is made for mobile :joy:


> btw.: what would be behind the "other" button?

Dunno yet, maybe some remote data samples, how you can use simple column with custom column.


> The above mentioned menu would of course be special to v-grid or at least libraries which support multiple approaches of implementing their components. I don't think this is a general feature for all catalogs.

For plugins that isnt bridges its practical to have different demos in separate folders, its really easy to skip if not wated, pretty much just to comment out 3-5 lines in the index.html that repeat the router.navigation

**Comment by Thanood** [comment]
Since I cannot create issues in my fork:
. [ ] disable variations row if `supportsVariations !== true`

**Comment by Thanood** [comment]
Current state:

image

**Comment by vegarringdal** [comment]
Great work @Thanood  :+1: 
This is really helpful for me when I try and move over, thx

**Comment by adriatic** [comment]
@vegarringdal @Thanood - please check the email based invitation to the aurelia-v-grid ui collaboration project in moqups

**Pull request merged**
